{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rag.fullname" . }}-job-reader
  labels:
    {{- include "rag.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rag.fullname" . }}-job-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "rag.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

